[package]
name = "blueshift_pinocchio_flash_loan"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
pinocchio = "0.8.4"
pinocchio-system = "0.2.3"
pinocchio-token = "0.3.0"
